-- ╭──────────────────────────────────────────────────────────────────────────╮
-- │                                                                          │
-- │   T H E M E                                                              │
-- │   colourscheme · generated from the active palette                       │
-- │                                                                          │
-- │   github.com/andreumassanet/impasto                                      │
-- │                                                                          │
-- ╰──────────────────────────────────────────────────────────────────────────╯

-- The colourscheme is generated by theme_manager.py into the shell's state
-- directory, which is added to the runtimepath so nothing generated lands in
-- ~/.config/nvim.

local state = vim.env.XDG_STATE_HOME or (vim.env.HOME .. "/.local/state")

local M = {}

-- · exported for lazy.lua, which has to re-add it after lazy.nvim resets
--   the runtimepath
M.dir = state .. "/quickshell/nvim"

vim.opt.runtimepath:append(M.dir)


-- ── COLORSCHEME ─────────────────────────────────────────────────────────────

-- · absent until the shell's first palette push
pcall(vim.cmd.colorscheme, "impasto")


-- ── TRANSPARENCY ────────────────────────────────────────────────────────────

-- · clear backgrounds so kitty's translucent window shows through. Run on
--   every ColorScheme event so it survives live repaints.
local transparent = {
    "Normal", "NormalNC", "NormalFloat", "FloatBorder", "SignColumn",
    "EndOfBuffer", "StatusLine", "StatusLineNC", "TabLine", "TabLineFill",
    "FoldColumn", "LineNr", "CursorLineNr",
}

local function clear_grounds()
    for _, group in ipairs(transparent) do
        local ok, hl = pcall(vim.api.nvim_get_hl, 0, { name = group })
        if ok then
            hl.bg = nil
            hl.ctermbg = nil
            pcall(vim.api.nvim_set_hl, 0, group, hl)
        end
    end
end

vim.api.nvim_create_autocmd("ColorScheme", {
    group = vim.api.nvim_create_augroup("impasto_ground", { clear = true }),
    callback = clear_grounds,
})

clear_grounds()

return M
